// Mock data from project-kronospan-data.json
// Project: 1-П-08/25-С Склад Kronospan Могилев

export const kronoshanProjectData = {
  project: {
    project_id: "c2cb859b-b3a0-4380-83d0-6140255e8471",
    project_name: "1-П-08/25-С Склад Kronospan Могилев",
    stages: [
      {
        stage_id: "c51bfbf1-67a1-43f8-9f99-8d52599f13ac",
        stage_name: "Стадия С",
        stage_description: null,
        objects: [
          {
            object_id: "3e32bdf8-6e99-47ca-a357-b9d0c78abc9d",
            object_name: "1. [Курирование]",
            object_description: "",
            sections: [
              {
                section_id: "8ed7e333-0b81-4425-a9a5-c0ca9a12fe20",
                section_name: "АВТ 08/25-С",
                section_description: null,
                section_type: null,
                section_start_date: null,
                section_end_date: null,
                responsible: {
                  user_id: "15f66016-5b31-44ea-b96e-582784e5fe71",
                  first_name: "Максим",
                  last_name: "Антонов",
                },
                decomposition_stages: [
                  {
                    decomposition_stage_id: "gen-stage-avt-1",
                    decomposition_stage_name: "Подготовка исходных данных",
                    decomposition_stage_description: "Сбор и анализ исходных данных для автоматизации",
                    decomposition_stage_start: "2025-02-01",
                    decomposition_stage_finish: "2025-02-15",
                    decomposition_stage_order: 1,
                    decomposition_items: [
                      {
                        decomposition_item_id: "gen-item-avt-1-1",
                        decomposition_item_description: "Анализ технического задания",
                        decomposition_item_planned_hours: 8,
                        decomposition_item_planned_due_date: "2025-02-05",
                        decomposition_item_order: 1,
                        decomposition_item_progress: 0,
                        work_category_name: "Управление",
                      },
                      {
                        decomposition_item_id: "gen-item-avt-1-2",
                        decomposition_item_description: "Сбор исходных данных от смежных разделов",
                        decomposition_item_planned_hours: 16,
                        decomposition_item_planned_due_date: "2025-02-10",
                        decomposition_item_order: 2,
                        decomposition_item_progress: 0,
                        work_category_name: "Исследования",
                      },
                    ],
                  },
                  {
                    decomposition_stage_id: "gen-stage-avt-2",
                    decomposition_stage_name: "Разработка проектной документации",
                    decomposition_stage_description: "Проектирование систем автоматизации",
                    decomposition_stage_start: "2025-02-16",
                    decomposition_stage_finish: "2025-03-31",
                    decomposition_stage_order: 2,
                    decomposition_items: [
                      {
                        decomposition_item_id: "gen-item-avt-2-1",
                        decomposition_item_description: "Разработка структурных схем",
                        decomposition_item_planned_hours: 24,
                        decomposition_item_planned_due_date: "2025-02-28",
                        decomposition_item_order: 1,
                        decomposition_item_progress: 0,
                        work_category_name: "Проектирование",
                      },
                      {
                        decomposition_item_id: "gen-item-avt-2-2",
                        decomposition_item_description: "3D-моделирование",
                        decomposition_item_planned_hours: 40,
                        decomposition_item_planned_due_date: "2025-03-15",
                        decomposition_item_order: 2,
                        decomposition_item_progress: 0,
                        work_category_name: "Моделирование 300",
                      },
                      {
                        decomposition_item_id: "gen-item-avt-2-3",
                        decomposition_item_description: "Оформление чертежей",
                        decomposition_item_planned_hours: 32,
                        decomposition_item_planned_due_date: "2025-03-31",
                        decomposition_item_order: 3,
                        decomposition_item_progress: 0,
                        work_category_name: "Детализация",
                      },
                    ],
                  },
                ],
              },
              {
                section_id: "c3e0afca-3057-402e-8c4a-da6e519d21b4",
                section_name: "ТХ 08/25-С",
                section_description: null,
                section_type: null,
                section_start_date: null,
                section_end_date: null,
                responsible: null,
                decomposition_stages: [
                  {
                    decomposition_stage_id: "gen-stage-th-1",
                    decomposition_stage_name: "Технологические решения",
                    decomposition_stage_description: "Разработка технологических решений склада",
                    decomposition_stage_start: "2025-02-01",
                    decomposition_stage_finish: "2025-03-15",
                    decomposition_stage_order: 1,
                    decomposition_items: [
                      {
                        decomposition_item_id: "gen-item-th-1-1",
                        decomposition_item_description: "Разработка технологической схемы",
                        decomposition_item_planned_hours: 24,
                        decomposition_item_planned_due_date: "2025-02-20",
                        decomposition_item_order: 1,
                        decomposition_item_progress: 0,
                        work_category_name: "Проектирование",
                      },
                      {
                        decomposition_item_id: "gen-item-th-1-2",
                        decomposition_item_description: "Спецификация оборудования",
                        decomposition_item_planned_hours: 16,
                        decomposition_item_planned_due_date: "2025-03-01",
                        decomposition_item_order: 2,
                        decomposition_item_progress: 0,
                        work_category_name: "Спецификации",
                      },
                    ],
                  },
                ],
              },
              {
                section_id: "c940531d-ec0a-4dab-afee-1b3e840bc4c3",
                section_name: "АПТ, СС 08/25-С",
                section_description: null,
                section_type: null,
                section_start_date: null,
                section_end_date: null,
                responsible: {
                  user_id: "71bcc6ae-2158-4caf-89fb-bc6b0c024681",
                  first_name: "Евгений",
                  last_name: "Аброськин",
                },
                decomposition_stages: [
                  {
                    decomposition_stage_id: "gen-stage-apt-1",
                    decomposition_stage_name: "Пожарная автоматика",
                    decomposition_stage_description: "Разработка систем АПТ и СС",
                    decomposition_stage_start: "2025-02-10",
                    decomposition_stage_finish: "2025-04-15",
                    decomposition_stage_order: 1,
                    decomposition_items: [
                      {
                        decomposition_item_id: "gen-item-apt-1-1",
                        decomposition_item_description: "Расчет пожарной нагрузки",
                        decomposition_item_planned_hours: 16,
                        decomposition_item_planned_due_date: "2025-02-25",
                        decomposition_item_order: 1,
                        decomposition_item_progress: 0,
                        work_category_name: "Расчёт",
                      },
                      {
                        decomposition_item_id: "gen-item-apt-1-2",
                        decomposition_item_description: "Схема размещения датчиков",
                        decomposition_item_planned_hours: 24,
                        decomposition_item_planned_due_date: "2025-03-15",
                        decomposition_item_order: 2,
                        decomposition_item_progress: 0,
                        work_category_name: "Проектирование",
                      },
                    ],
                  },
                ],
              },
              {
                section_id: "3d225767-7eb6-4dd1-a443-22ebe12786d4",
                section_name: "ОВ 08/25-С",
                section_description: null,
                section_type: null,
                section_start_date: null,
                section_end_date: null,
                responsible: {
                  user_id: "52869929-f050-4c22-804e-ec667047b519",
                  first_name: "Евгений",
                  last_name: "Усс",
                },
                decomposition_stages: [
                  {
                    decomposition_stage_id: "gen-stage-ov-1",
                    decomposition_stage_name: "Отопление и вентиляция",
                    decomposition_stage_description: "Проектирование систем ОВ",
                    decomposition_stage_start: "2025-02-15",
                    decomposition_stage_finish: "2025-04-30",
                    decomposition_stage_order: 1,
                    decomposition_items: [
                      {
                        decomposition_item_id: "gen-item-ov-1-1",
                        decomposition_item_description: "Теплотехнический расчет",
                        decomposition_item_planned_hours: 20,
                        decomposition_item_planned_due_date: "2025-03-01",
                        decomposition_item_order: 1,
                        decomposition_item_progress: 0,
                        work_category_name: "Расчёт",
                      },
                      {
                        decomposition_item_id: "gen-item-ov-1-2",
                        decomposition_item_description: "3D-модель воздуховодов",
                        decomposition_item_planned_hours: 32,
                        decomposition_item_planned_due_date: "2025-03-20",
                        decomposition_item_order: 2,
                        decomposition_item_progress: 0,
                        work_category_name: "Моделирование 300",
                      },
                    ],
                  },
                ],
              },
              {
                section_id: "4c6b92aa-e0d6-49eb-9431-f3ff9be08300",
                section_name: "СС 08/25-С",
                section_description: null,
                section_type: null,
                section_start_date: null,
                section_end_date: null,
                responsible: null,
                decomposition_stages: [],
              },
              {
                section_id: "1942cc06-25f9-47e6-9faf-73720fcece10",
                section_name: "ВК/НВК 08/25-С",
                section_description: null,
                section_type: null,
                section_start_date: null,
                section_end_date: null,
                responsible: {
                  user_id: "b3872fe0-d019-4866-82cc-38b0ba49a29c",
                  first_name: "Александр",
                  last_name: "Тимошук",
                },
                decomposition_stages: [
                  {
                    decomposition_stage_id: "gen-stage-vk-1",
                    decomposition_stage_name: "Водоснабжение и канализация",
                    decomposition_stage_description: "Проектирование систем ВК",
                    decomposition_stage_start: "2025-03-01",
                    decomposition_stage_finish: "2025-05-15",
                    decomposition_stage_order: 1,
                    decomposition_items: [
                      {
                        decomposition_item_id: "gen-item-vk-1-1",
                        decomposition_item_description: "Гидравлический расчет",
                        decomposition_item_planned_hours: 16,
                        decomposition_item_planned_due_date: "2025-03-20",
                        decomposition_item_order: 1,
                        decomposition_item_progress: 0,
                        work_category_name: "Расчёт",
                      },
                      {
                        decomposition_item_id: "gen-item-vk-1-2",
                        decomposition_item_description: "План сетей ВК",
                        decomposition_item_planned_hours: 24,
                        decomposition_item_planned_due_date: "2025-04-10",
                        decomposition_item_order: 2,
                        decomposition_item_progress: 0,
                        work_category_name: "Проектирование",
                      },
                    ],
                  },
                ],
              },
              {
                section_id: "988cf4d0-5d1e-47ad-86ac-a79689b9b71d",
                section_name: "КР 08/25-С",
                section_description: null,
                section_type: null,
                section_start_date: null,
                section_end_date: null,
                responsible: {
                  user_id: "b3872fe0-d019-4866-82cc-38b0ba49a29c",
                  first_name: "Александр",
                  last_name: "Тимошук",
                },
                decomposition_stages: [
                  {
                    decomposition_stage_id: "gen-stage-kr-1",
                    decomposition_stage_name: "Конструктивные решения",
                    decomposition_stage_description: "Разработка конструктивных решений",
                    decomposition_stage_start: "2025-02-01",
                    decomposition_stage_finish: "2025-06-30",
                    decomposition_stage_order: 1,
                    decomposition_items: [
                      {
                        decomposition_item_id: "gen-item-kr-1-1",
                        decomposition_item_description: "Расчет несущих конструкций",
                        decomposition_item_planned_hours: 40,
                        decomposition_item_planned_due_date: "2025-03-15",
                        decomposition_item_order: 1,
                        decomposition_item_progress: 0,
                        work_category_name: "Расчёт",
                      },
                      {
                        decomposition_item_id: "gen-item-kr-1-2",
                        decomposition_item_description: "3D-модель каркаса",
                        decomposition_item_planned_hours: 80,
                        decomposition_item_planned_due_date: "2025-04-30",
                        decomposition_item_order: 2,
                        decomposition_item_progress: 0,
                        work_category_name: "Моделирование 400",
                      },
                      {
                        decomposition_item_id: "gen-item-kr-1-3",
                        decomposition_item_description: "Рабочие чертежи КР",
                        decomposition_item_planned_hours: 60,
                        decomposition_item_planned_due_date: "2025-06-15",
                        decomposition_item_order: 3,
                        decomposition_item_progress: 0,
                        work_category_name: "Детализация",
                      },
                    ],
                  },
                ],
              },
              {
                section_id: "1beeff7f-99e0-4c83-b1e3-0066cb08dbcd",
                section_name: "ЭС 08/25-С",
                section_description: null,
                section_type: null,
                section_start_date: null,
                section_end_date: null,
                responsible: {
                  user_id: "f27d83b2-a129-42bd-9fd3-bee4513981d0",
                  first_name: "Тихон",
                  last_name: "Бобров",
                },
                decomposition_stages: [
                  {
                    decomposition_stage_id: "gen-stage-es-1",
                    decomposition_stage_name: "Электроснабжение",
                    decomposition_stage_description: "Проектирование систем ЭС",
                    decomposition_stage_start: "2025-02-15",
                    decomposition_stage_finish: "2025-05-30",
                    decomposition_stage_order: 1,
                    decomposition_items: [
                      {
                        decomposition_item_id: "gen-item-es-1-1",
                        decomposition_item_description: "Расчет электрических нагрузок",
                        decomposition_item_planned_hours: 24,
                        decomposition_item_planned_due_date: "2025-03-10",
                        decomposition_item_order: 1,
                        decomposition_item_progress: 0,
                        work_category_name: "Расчёт",
                      },
                      {
                        decomposition_item_id: "gen-item-es-1-2",
                        decomposition_item_description: "Однолинейные схемы",
                        decomposition_item_planned_hours: 32,
                        decomposition_item_planned_due_date: "2025-04-15",
                        decomposition_item_order: 2,
                        decomposition_item_progress: 0,
                        work_category_name: "Проектирование",
                      },
                    ],
                  },
                ],
              },
              {
                section_id: "3193e5d4-f2d0-49cb-aa67-b2b2807e18e3",
                section_name: "АР 08/25-С",
                section_description: null,
                section_type: null,
                section_start_date: null,
                section_end_date: null,
                responsible: {
                  user_id: "1dce2d76-c033-487e-956e-94466bc0e21a",
                  first_name: "Наталья",
                  last_name: "Мирончик",
                },
                decomposition_stages: [
                  {
                    decomposition_stage_id: "gen-stage-ar-1",
                    decomposition_stage_name: "Архитектурные решения",
                    decomposition_stage_description: "Разработка архитектурных решений",
                    decomposition_stage_start: "2025-02-01",
                    decomposition_stage_finish: "2025-04-30",
                    decomposition_stage_order: 1,
                    decomposition_items: [
                      {
                        decomposition_item_id: "gen-item-ar-1-1",
                        decomposition_item_description: "Концептуальное решение фасадов",
                        decomposition_item_planned_hours: 16,
                        decomposition_item_planned_due_date: "2025-02-20",
                        decomposition_item_order: 1,
                        decomposition_item_progress: 0,
                        work_category_name: "Проектирование",
                      },
                      {
                        decomposition_item_id: "gen-item-ar-1-2",
                        decomposition_item_description: "3D-модель здания",
                        decomposition_item_planned_hours: 40,
                        decomposition_item_planned_due_date: "2025-03-15",
                        decomposition_item_order: 2,
                        decomposition_item_progress: 0,
                        work_category_name: "Моделирование 400",
                      },
                      {
                        decomposition_item_id: "gen-item-ar-1-3",
                        decomposition_item_description: "Рабочие чертежи АР",
                        decomposition_item_planned_hours: 32,
                        decomposition_item_planned_due_date: "2025-04-20",
                        decomposition_item_order: 3,
                        decomposition_item_progress: 0,
                        work_category_name: "Детализация",
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
}
